config/routes.rb
require "resque/server"
require "resque/scheduler/server"

Rails.application.routes.draw do
  root to: "pages#top"
  get "about", to: "pages#about"
  get "help/bulk", to: "pages#help_bulk"

  resources :nodes do
    member do
      post "transfer"
    end
    resource :confirmation, only: [:new, :edit, :create, :update]
    resource :specific_node_application, only: [:new, :create]
    resource :host
    resources :components, only: [:index, :show, :new, :update, :destroy]
  end
  resources :nics, only: [:show, :new]

  resources :networks
  resources :ipv4_pools, only: [:new]
  resources :ipv6_pools, only: [:new]

  resources :bulks, only: [:index, :show, :create, :destroy] do
    member do
      put "cancel"
    end
  end

  defaults format: :json do
    resources :places, only: [:index, :show, :create, :update, :destroy]
    resources :hardwares, only: [:index, :show, :create, :update, :destroy]
    resources :operating_systems,
      only: [:index, :show, :create, :update, :destroy]
    resources :security_softwares,
      only: [:index, :show, :create, :update, :destroy]
    resources :device_types, only: [:index, :show, :create, :update, :destroy]
    resources :os_categories, only: [:index, :show, :create, :update, :destroy]
  end

  namespace "manage" do
    get "places"
    get "hardwares"
    get "operating_systems"
    get "security_softwares"
    get "device_types"
    get "os_categories"
  end

  resources :users, only: [:index, :show, :edit, :update] do
    collection do
      put "sync"
    end
    resources :use_networks, only: [:create, :update, :destroy]
  end

  resource :user, only: [:show]

  devise_for :users, path: "auth"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  authenticated :user, ->(user) { user.admin? } do
    mount Resque::Server, at: "/jobs"
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  include Search

  include NodeParameter

  before_action :set_node, only: [:show, :edit, :update, :destroy, :transfer]
  before_action :authorize_node, only: [:index]

  search_for Node

  # GET /nodes
  # GET /nodes.json
  # GET /nodes.csv
  def index
    set_search
    @nodes = search(policy_scope(Node)).includes(:user, :place, :hardware,
      :operating_system, :confirmation, nics: :network)
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    new_nic_params = {}
    if (network = current_user.default_network)
      new_nic_params.merge!({network_id: network.id, auth: network.auth,
      ipv4_config: (Nic.ipv4_configs.keys & network.ipv4_configs).first,
      ipv6_config: (Nic.ipv6_configs.keys & network.ipv6_configs).first,})
    end
    nic = Nic.new(**new_nic_params)

    @node = Node.new(
      place: Place.new,
      hardware: Hardware.new,
      operating_system: OperatingSystem.new,
      nics: [nic],
      user: current_user)
    @node.node_type = "mobile" if current_user.guest?
    authorize @node
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)
    @node.user = current_user unless current_user.admin?
    authorize @node

    respond_to do |format|
      if @node.save
        format.turbo_stream do
          flash.now.notice = t_success(@node, :register)
        end
        format.html do
          redirect_to @node, notice: t_success(@node, :register)
        end
        format.json { render :show, status: :created, location: @node }
      else
        format.html do
          flash.now.alert = t_failure(@node, :register)
          render :new
        end
        format.json { render json: @node.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.turbo_stream do
          flash.now.notice = t_success(@node, :update)
        end
        format.html do
          redirect_to @node, notice: t_success(@node, :update)
        end
        format.json { render :show, status: :ok, location: @node }
      else
        format.html do
          flash.now.alert = t_failure(@node, :update)
          render :edit
        end
        format.json { render json: @node.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    respond_to do |format|
      if @node.specific
        format.html do
          redirect_to @node,
            alert: t("errors.messages.not_delete_specific_node")
        end
        format.json { render json: @node.errors, status: :unprocessable_content }
      elsif @node.destroy
        if current_user.id == @node.user_id
          # nodes_countが変更されているため、reloadする。
          current_user.reload
        end
        format.turbo_stream do
          flash.now.notice = t_success(@node, :delete)
        end
        format.html do
          redirect_to nodes_url, notice: t_success(@node, :delete)
        end
        format.json { head :no_content }
      else
        format.html do
          redirect_to @node, alert: t_failure(@node, :delete)
        end
        format.json { render json: @node.errors, status: :unprocessable_content }
      end
    end
  end

  # POST /nodes/1/tranfer
  def transfer
    permitted_params = params.permit(:username, :note)
    user = User.find_by(username: permitted_params[:username])
    note = permitted_params[:note]

    if user.nil?
      respond_to do |format|
        format.html do
          redirect_to @node, alert: t("errors.messages.not_found_user")
        end
        format.json do
          errors = {username: t("errors.messages.not_found_user")}
          render json: errors, status: :unprocessable_content
        end
      end
    elsif user.guest?
      respond_to do |format|
        format.html do
          redirect_to(@node,
            alert: t("errors.messages.cannot_transfer_to_guest"))
        end
        format.json do
          errors = {username: t("errors.messages.cannot_transfer_to_guest")}
          render json: errors, status: :unprocessable_content
        end
      end
    else
      @node.user = user
      @node.confirmation = nil
      if note.present?
        @node.note =
          if @node.note.blank?
            note
          elsif @node.note.end_with?("\n")
            @node.note + note
          else
            [@node.note, note].join("\n")
          end
      end
      respond_to do |format|
        if @node.save
          format.html do
            redirect_to nodes_path, notice: t_success(@node, :transfer)
          end
          format.json { render :show, status: :ok, location: @node }
        else
          format.html do
            redirect_to @node, alert: t_failure(@node, :transfer)
          end
          format.json do
            render json: @node.errors, status: :unprocessable_content
          end
        end
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_node
    @node = policy_scope(Node)
      .includes(:user, :place, :hardware, :operating_system, nics: :network)
      .find(params[:id])
    authorize @node
  end

  # Only allow a list of trusted parameters through.
  private def node_params
    permitted_params = params.expect(node: [
      :name,
      :hostname,
      :domain,
      :duid,
      :node_type,
      :disabled,
      :permanent,
      :specific,
      :public,
      :dns,
      :note,
      :user_id,
      :host_id,
      component_ids: [],
      place: [:area, :building, :floor, :room],
      hardware: [:device_type_id, :maker, :product_name, :model_number],
      operating_system: [:os_category_id, :name],
      nics_attributes: [[
        :id,
        :_destroy,
        :name,
        :locked,
        :interface_type,
        :auth,
        :mac_address,
        :network_id,
        :ipv4_config,
        :ipv4_address,
        :ipv6_config,
        :ipv6_address,
      ]],
    ])

    normalize_node_params(permitted_params)
  end

  private def authorize_node
    authorize Node
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
  NODE_LIST_COLS = [
    {name: :user,         grid: [0, 0, 2, 2, 1, 1]},
    {name: :name,         grid: [4, 3, 3, 3, 3, 2], sort: :name},
    {name: :hostname,     grid: [3, 3, 2, 2, 2, 1], sort: :hostname},
    {name: :place,        grid: [0, 0, 0, 0, 0, 1]},
    {name: :ipv4_address, grid: [5, 4, 3, 2, 2, 2], sort: :nics_ipv4},
    {name: :ipv6_address, grid: [0, 0, 0, 0, 3, 2], sort: :nics_ipv6},
    {name: :mac_address,  grid: [0, 0, 0, 0, 0, 2], sort: :nics_mac_address},
    {name: :confirmation, grid: [0, 2, 2, 2, 1, 1]},
  ].freeze

  # when confirmation feature is disabled
  NODE_WITHOUT_CONFIRMATION_LIST_COLS = [
    {name: :user,         grid: [0, 0, 2, 2, 1, 1]},
    {name: :name,         grid: [4, 4, 3, 3, 3, 2], sort: :name},
    {name: :hostname,     grid: [3, 3, 3, 3, 2, 1], sort: :hostname},
    {name: :place,        grid: [0, 0, 0, 0, 0, 1]},
    {name: :ipv4_address, grid: [5, 5, 4, 4, 2, 2], sort: :nics_ipv4},
    {name: :ipv6_address, grid: [0, 0, 0, 0, 4, 3], sort: :nics_ipv6},
    {name: :mac_address,  grid: [0, 0, 0, 0, 0, 2], sort: :nics_mac_address},
  ].freeze

  NODE_ACTION_LIST_COLS = [
    {name: :user,         grid: [0, 0, 2, 2, 1, 1]},
    {name: :name,         grid: [6, 3, 3, 3, 3, 2]},
    {name: :hostname,     grid: [4, 3, 2, 2, 2, 1]},
    {name: :ipv4_address, grid: [0, 4, 3, 3, 2, 2]},
    {name: :ipv6_address, grid: [0, 0, 0, 0, 3, 3]},
    {name: :mac_address,  grid: [0, 0, 0, 0, 0, 2]},
    {name: :action,       grid: [2, 2, 2, 2, 1, 1]},
  ].freeze

  NODE_DOUBLE_ACTION_LIST_COLS = [
    {name: :name,         grid: [8, 4, 4, 4, 3, 2]},
    {name: :hostname,     grid: [0, 3, 2, 2, 2, 1]},
    {name: :ipv4_address, grid: [0, 0, 4, 4, 2, 2]},
    {name: :ipv6_address, grid: [0, 0, 0, 0, 3, 3]},
    {name: :mac_address,  grid: [0, 0, 0, 0, 0, 2]},
    {name: :action,       grid: [4, 3, 2, 2, 2, 2]},
  ].freeze

  LIST_COL_CLASSES = {
    user:         %w[d-none d-md-block col-md-2 col-lg-2 col-xl-1 col-xxl-1],
    name:         %w[col-4 col-sm-3 col-md-3 col-lg-3 col-xl-3 col-xxl-2],
    hostname:     %w[col-3 col-sm-3 col-md-2 col-lg-2 col-xl-2 col-xxl-1],
    place:        %w[d-none d-xxl-block col-xxl-1],
    ipv4_address: %w[col-5 col-sm-4 col-md-3 col-lg-2 col-xl-2 col-xxl-2],
    ipv6_address: %w[d-none d-xl-block col-xl-3 col-xxl-2],
    mac_address:  %w[d-none d-xxl-block col-xxl-2],
    confirmation: %w[d-none d-sm-block col-sm-2 col-md-2 col-lg-2 col-xl-1 col-xxl-1],
  }.freeze

  def node_list_cols
    if Settings.feature.confirmation
      NODE_LIST_COLS
    else
      NODE_WITHOUT_CONFIRMATION_LIST_COLS
    end
  end

  def node_type_names
    names = %i[normal mobile]
    names << :virtual if Settings.feature.virtual_node
    names << :logical if Settings.feature.logical_node
    names
  end

  def node_flag_names
    attributes = %i[disabled permanent public dns]
    attributes << :specific if Settings.feature.specific_node
    attributes
  end

  def list_col_classes(name, cols: node_list_cols)
    grid_classes(cols.find { |col| col[:name] == name }[:grid])
  end

  def installation_methods(node)
    if node.operating_system
      policy_scope(SecuritySoftware)
        .where(os_category: node.operating_system.os_category)
        .distinct
        .pluck(:installation_method)
    else
      []
    end
  end

  def init_confirmation(node)
    confirmation = node.solid_confirmation
    # check os
    if node.operating_system.nil?
      confirmation.security_software = nil
      confirmation.security_update = nil
      confirmation.security_scan = nil
    elsif confirmation.security_software&.os_category != node.operating_system.os_category
      confirmation.security_software = SecuritySoftware.new(os_category: node.operating_system.os_category)
      confirmation.security_update = nil
      confirmation.security_scan = nil
    end
    reset_unknown_confirmation(confirmation)
  end

  private def reset_unknown_confirmation(confirmation)
    Confirmation::NUM_ATTRS.each do |name|
      confirmation.send("#{name}=", nil) if confirmation.send(name) == "unknown"
    end
    confirmation.security_hardware = nil if confirmation.security_hardwares&.include?("unknown")
    confirmation
  end

  def node_name_decorated(node)
    type_badge = badge_for(node, :node_type, hidden: node.normal?)
    node_flag_names.map { |name| badge_for(node, name) }.inject(h(node.name) + type_badge, :+)
  end

  def node_ipv4_address_decorated(node)
    node.nics.map do |nic|
      if nic.ipv4_dynamic?
        tag.span(t_enum(:dynamic, :ipv4_config), class: "text-success-emphasis")
      else
        span_value_for(nic.ipv4, blank_alt: "")
      end
    end.inject { |result, item| result + tag.br + item }
  end

  def node_ipv6_address_decorated(node)
    node.nics.map do |nic|
      if nic.ipv6_dynamic?
        tag.span(t_enum(:dynamic, :ipv6_config), class: "text-success-emphasis")
      else
        span_value_for(nic.ipv6, blank_alt: "")
      end
    end.inject { |result, item| result + tag.br + item }
  end

  def node_confirmation_decorated(node)
    case node.solid_confirmation.status
    when :unconfirmed
      tag.i(class: "fas fa-times-circle text-danger-emphasis") +
        tag.span(t("messages.unconfirmed"), class: "text-danger-emphasis")
    when :expired
      tag.i(class: "fas fa-times-circle text-danger-emphasis") +
        tag.span(t("messages.expired"), class: "text-danger-emphasis")
    when :unapproved
      tag.i(class: "fas fa-exclamation-triangle text-warning-emphasis") +
        tag.span(t("messages.unapproved"), class: "text-warning-emphasis")
    when :expire_soon
      tag.i(class: "fas fa-exclamation-triangle text-warning-emphasis") +
        tag.span(t("messages.expire_soon"), class: "text-warning-emphasis")
    when :approved
      tag.i(class: "fas fa-check text-success-emphasis") +
        tag.span(t("messages.approved"), class: "text-success-emphasis")
    end
  end

  def node_mac_address_decorated(node)
    node.nics.map { |nic| h(nic.mac_address) }
      .inject { |result, item| result + tag.br + item }
  end

  def node_list_for(nodes,
    write_headers: true, pagination: :both, cols: node_list_cols,
    wrapper: {}, action: nil, &block)
    pagination = :both if pagination == true
    tag.div(**wrapper) do
      contents = []
      contents << paginate(nodes) if [:both, :above].include?(pagination)
      contents << node_list_table_for(nodes, write_headers:, cols:, action:,
        &block)
      contents << paginate(nodes) if [:both, :below].include?(pagination)
      contents << tag.p(page_entries_info(nodes)) if pagination
      contents.inject(:+)
    end
  end

  def node_list_table_for(nodes, write_headers: true, cols: node_list_cols,
    action: nil)
    tag.div(class: "mb-2") do
      rows = []
      rows << node_list_headers_for(cols:) if write_headers
      nodes.each do |node|
        rows <<
          if block_given?
            capture { yield node }
          else
            node_list_col_for(node, cols:, action:)
          end
      end
      rows.inject(:+)
    end
  end

  def node_list_headers_for(cols: node_list_cols)
    tag.div(class: "row py-1 border-bottom fw-bold") do
      cols.map do |col|
        name = col[:name]
        opts = {class: col_grid_class(col)}
        content =
          case name
          when :action
            t("messages.action")
          when :ipv4_address, :ipv6_address, :mac_address
            h(Nic.human_attribute_name(name))
          else
            h(Node.human_attribute_name(name))
          end
        content += h(" ") + sort_link(col[:sort]) if col[:sort]
        tag.div(content, **opts)
      end.inject(:+)
    end
  end

  def node_list_col_for(node, cols: node_list_cols, link: nil, action: nil)
    content = cols.map do |col|
      name = col[:name]
      opts = {class: col_grid_class(col)}
      case name
      when :action
        if block_given?
          tag.div(**opts) { yield node }
        else
          tag.div(action&.call(node), **opts)
        end
      when :user
        tag.div(node.user&.username, **opts)
      when :name
        tag.div(node_name_decorated(node), **opts)
      when :place
        tag.div(node.place&.short_name, **opts)
      when :confirmation
        tag.div(node_confirmation_decorated(node), **opts)
      when :ipv4_address
        tag.div(node_ipv4_address_decorated(node), **opts)
      when :ipv6_address
        tag.div(node_ipv6_address_decorated(node), **opts)
      when :mac_address
        tag.div(node_mac_address_decorated(node), **opts)
      else
        tag.div(node.__send__(name), **opts)
      end
    end.inject(:+)

    if link
      link_to(content, link, class: "row py-1 border-bottom",
        data: {turbo: false})
    else
      tag.div(content, class: "row py-1 border-bottom")
    end
  end
end

app/views/nodes/_form_components.html.slim
.rounded.border.p-2.mb-2
  h4 = t("forms.node.components.title")
  .mb-2: small.text-muted = t("forms.node.components.help")
  = render "components/list", form: form

app/views/nodes/_form_hardware.slim
.rounded.border.p-2.mb-2[
  data-controller="datalist-candidate"
  data-datalist-candidate-url-value="#{hardwares_path}"
]
  = form.fields_for :hardware, form.object.hardware || Hardware.new do |field|
    - order = {nodes_count: :desc}
    h4 = t("forms.node.hardware.title")
    .mb-2: small.text-muted = t("forms.node.hardware.help")
    .row
      .col-md-3
        = field.collection_select :device_type_id, DeviceType.order(:order), :id, :name,
          {include_blank: "(未選択)", floating: true}, required: false,
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
      .col-md-2
        = field.text_field :maker,
          floating: true,
          list: "#{field.field_id(:maker)}-list",
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
        datalist id="#{field.field_id(:maker)}-list" data-datalist-candidate-target="datalist"
          - candidate_values(field.object, :maker, [:device_type_id], order:).each do |name|
            option = name
      .col-md-4
        = field.text_field :product_name,
          floating: true,
          list: "#{field.field_id(:product_name)}-list",
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
        datalist id="#{field.field_id(:product_name)}-list" data-datalist-candidate-target="datalist"
          - candidate_values(field.object, :product_name, [:device_type_id, :maker], order:).each do |name|
            option = name
      .col-md-3
        = field.text_field :model_number,
          floating: true,
          list: "#{field.field_id(:model_number)}-list",
          data: {datalist_candidate_target: "input"}
        datalist id="#{field.field_id(:model_number)}-list" data-datalist-candidate-target="datalist"
          - candidate_values(field.object, :model_number, [:device_type_id, :maker, :product_name],
              order:).each do |name|
            option = name

app/views/nodes/_form_host.html.slim
.rounded.border.p-2.mb-2
  h4 = t("forms.node.host.title")
  .mb-2: small.text-muted = t("forms.node.host.help")
  = render "hosts/host", form: form

app/views/nodes/_form_nics.html.slim
.rounded.border.p-2.mb-2
  h4 = t("forms.node.nic.title")
  .mb-2: small.text-muted = t("forms.node.nic.help")
  .row
    .col-md-4
      = form.text_field :duid, floating: true, pattern: duid_pattern
    .col.text-end
      = link_to t("with_actions.add", name: Nic.model_name.human), new_nic_path,
        class: ["btn", "btn-secondary", current_user.guest? && "d-none"],
        data: {turbo: true, turbo_stream: true}

  = turbo_frame_tag "nics"
    = form.fields_for :nics do |field|
      - if current_user.admin? || !field.object.locked
        = render "nics/form", form: field
      - else
        .rounded.border.p-2.mb-2
          .row.mb-2: .col
            small.text-muted< = t("messages.node_nic_locked")
          .row: .col.px-3
            = render field.object

  script#node-nic-messages type="application/json"
    == { \
      config_helps: t("messages.node_nic_config_helps"),
      helps: t("messages.node_nic_helps"),
    }.to_json

app/views/nodes/_form_operating_system.html.slim
- locked_os_category_ids = OsCategory.where(locked: true).pluck(:id)
.rounded.border.p-2.mb-2[
  data-controller="datalist-candidate"
  data-datalist-candidate-url-value="#{operating_systems_path}"
  data-datalist-candidate-previous-value="ture"
  data-datalist-candidate-clear-value="ture"
]
  = form.fields_for :operating_system, form.object.operating_system || OperatingSystem.new do |field|
    h4 = t("forms.node.operating_system.title")
    .mb-2: small.text-muted = t("forms.node.operating_system.help")
    .row
      .col-md-4
        = field.collection_select :os_category_id, OsCategory.order(:order), :id, :name,
          {include_blank: "(未選択)", floating: true}, required: false,
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
      .col-md-3
        = field.text_field :name,
          floating: true,
          disabled: field.object.os_category_id.nil?,
          required: false,
          readonly: field.object.os_category&.locked?,
          list: "#{field.field_id(:name)}-list",
          aria: {describedby: "#{field.field_id(:name)}-description"},
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
        datalist id="#{field.field_id(:name)}-list" data-datalist-candidate-target="datalist"
          - candidate_values(field.object, :name, [:os_category_id], order: {nodes_count: :desc}).each do |name|
            option = name
    small.form-text id="#{field.field_id(:name)}-description" data-datalist-candidate-target="description"
      = field.object.description

app/views/nodes/_form_place.html.slim
.rounded.border.p-2.mb-2[
  data-controller="datalist-candidate"
  data-datalist-candidate-url-value="#{places_path}"
]
  = form.fields_for :place, form.object.place || Place.new do |field|
    - order = {nodes_count: :desc}
    h4 = t("forms.node.place.title")
    .mb-2: small.text-muted = t("forms.node.place.help")
    .row
      .col-md-3
        = field.text_field :area,
          floating: true,
          list: "#{field.field_id(:area)}-list",
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
        datalist id="#{field.field_id(:area)}-list" data-datalist-candidate-target="datalist"
          - candidate_values(field.object, :area, order:).each do |name|
            option = name
      .col-md-3
        = field.text_field :building,
          floating: true,
          list: "#{field.field_id(:building)}-list",
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
        datalist id="#{field.field_id(:building)}-list" data-datalist-candidate-target="datalist"
          - candidate_values(field.object, :building, [:area], order:).each do |name|
            option = name
      .col-md-2
        - floor_list = 10.downto(-5).map { |i| [t_floor(i), i] }
        = field.select :floor, floor_list,
          {floating: true},
          data: {datalist_candidate_target: "input", action: "datalist-candidate#checkInputs"}
      .col-md-4
        = field.text_field :room,
          floating: true,
          list: "#{field.field_id(:room)}-list",
          data: {datalist_candidate_target: "input"}
        datalist id="#{field.field_id(:room)}-list" data-datalist-candidate-target="datalist"
          - candidate_values(field.object, :room, [:area, :building, :floor], order:).each do |name|
            option = name

app/views/nodes/_help.html.slim
h3 設定のヘルプ

ul
  li 必要な情報は「端末名」とNIC情報についてのみですが、端末の「確認」で承認されるにはOS情報が必須になります。OS情報も入力してください。
  li ホスト名、設置場所、機器情報等は任意ですが、記載の情報をもとに問い合わせ等を行います。問い合わせ時に端末が確認することが出きる最低限の情報を記入しておいてください。
  li
    | IPv4設定・IPv6設定の設定はそれぞれ次のような意味です。
    dl
      dt 動的
      dd 接続する度にIPアドレスが変更されます。一般的なクライアント端末はこちらを選んでください。
      dt 予約
      dd MACアドレスに基づき常に同じIPアドレスを割り当てられます。MACアドレス(IPv6の場合はDUID)の入力が必須です。割り当てられるIPアドレスは、保存時に空いているIPアドレスが自動的に割り振られます。
      dt 固定
      dd 端末にIPアドレスを設定して接続します。保存時に空いているIPアドレスが自動的に割り振られます。
      dt 写像
      dd IPv4アドレスに基づき、IPv6アドレスを決定します。IPv4設定は固定または手動でなければなりません。IPv6のみ設定が可能です。
      dt 手動
      dd 管理者が手動でIPアドレスを割り振るときに設定します。利用者が新たに設定することはできません。
      dt 無効
      dd 無効とし、IPアドレスを割り当てません。
  li 特定端末の場合、関連するNICがロックされ、変更できません。変更が必要な場合は、特定端末の申請でその旨を備考欄に記載してください。
  li
    |
      HAクラスタ等によって複数の端末から共有される仮想的なIPアドレスの割当や実際には存在しない予約として仮想的な端末を登録する場合は、「仮想」にチェックを入れてください。
      「仮想」にチェックがある場合、実際の端末が存在しないため、設置場所、機器、OSは入力できません。

app/views/nodes/_list.html.slim
= turbo_frame_tag "nodes-list" do
  .mb-2
    .row.row-cols-md-auto.g-3
      - if Settings.feature.specific_node
        .col-12
          => filter_link(:specific)
          | 特定端末
      .col-12
        = filter_collection_select(:nics_network_id,
          current_user.usable_networks.to_a, :id, :name)
      - if current_user.admin?
        .col-12
          = filter_collection_select(:user_id, User.all, :id, :username)
  = node_list_for(nodes) do |node|
    = turbo_frame_tag dom_id(node, "nodes-list")
      = node_list_col_for(node, link: node)

app/views/nodes/copy.slim
h1 端末の新規登録(コピー)

p 端末名、ホスト名、MACアドレスを入力してください。

p
  | コピー元:
  =< @original_node.name

= render "form"

hr

= link_to "端末一覧に戻る", nodes_path

app/views/nodes/index.html.slim
- content_for :heading
  h2
    = Node.model_name.human
    = t("actions.index")

.mb-2
  .row.row-cols-md-auto.g-3.align-items-center
    .col-12
      = bootstrap_form_tag url: nodes_path, method: "get",
        data: {turbo_frame: "nodes-list"} do |f|
        - @per.present?
          = f.hidden_field("per", value: @per)
        - @order&.each do |name, value|
          = f.hidden_field("order[#{name}]", value: value)
        - @condition&.each do |name, value|
          = f.hidden_field("condition[#{name}]", value: value)
        = f.search_field :query, value: @query, hide_label: true,
          append: f.primary('<i class="fas fa-search"></i>'.html_safe, name: :search, render_as_button: true)
    - if current_user.node_creatable?
      .col-12.mb-3
        = link_to t("actions.new"), new_node_path, class: "btn btn-secondary"
    .col-12
      = bootstrap_form_with model: Bulk.new(target: "Node"), data: {turbo: false} do |f|
        = f.hidden_field :target
        = f.select :content_type, bulk_content_type_list,
          hide_label: true, prepend: t("forms.bulk.export"),
          append: f.primary('<i class="fa-solid fa-file-export"></i>'.html_safe, name: :commit, render_as_button: true)
- if Settings.feature.confirmation
  p 1年に1度、端末の確認を行ってください。

hr

= render "list", nodes: @nodes

app/views/nodes/new.html.slim
- content_for :heading
  h2 = Node.model_name.human

= render "form", node: @node

hr

=<> link_to t("actions.index"), nodes_path, class: "btn btn-secondary",
  data: {turbo: false}

app/views/nodes/show.html.slim
- content_for :heading
  h2 = Node.model_name.human

= render @node

hr

=<> link_to t("actions.index"), nodes_path, class: "btn btn-secondary",
  data: {turbo: false}

app/views/nodes/update.turbo_stream.slim
= turbo_stream.replace @node
= turbo_stream.update "flash", partial: "flash"
= turbo_stream_action_tag "visit", target: @node, url: node_path(@node), autoscroll: true,
  data: {turbo_action: :advance, autoscroll_block: "start"}