config/routes.rb
require "resque/server"
require "resque/scheduler/server"

Rails.application.routes.draw do
  root to: "pages#top"
  get "about", to: "pages#about"
  get "help/bulk", to: "pages#help_bulk"

  resources :nodes do
    member do
      post "transfer"
    end
    resource :confirmation, only: [:new, :edit, :create, :update]
    resource :specific_node_application, only: [:new, :create]
    resource :host
    resources :components, only: [:index, :show, :new, :update, :destroy]
  end
  resources :nics, only: [:show, :new]

  resources :networks
  resources :ipv4_pools, only: [:new]
  resources :ipv6_pools, only: [:new]

  resources :bulks, only: [:index, :show, :create, :destroy] do
    member do
      put "cancel"
    end
  end

  defaults format: :json do
    resources :places, only: [:index, :show, :create, :update, :destroy]
    resources :hardwares, only: [:index, :show, :create, :update, :destroy]
    resources :operating_systems,
      only: [:index, :show, :create, :update, :destroy]
    resources :security_softwares,
      only: [:index, :show, :create, :update, :destroy]
    resources :device_types, only: [:index, :show, :create, :update, :destroy]
    resources :os_categories, only: [:index, :show, :create, :update, :destroy]
  end

  namespace "manage" do
    get "places"
    get "hardwares"
    get "operating_systems"
    get "security_softwares"
    get "device_types"
    get "os_categories"
  end

  resources :users, only: [:index, :show, :edit, :update] do
    collection do
      put "sync"
    end
    resources :use_networks, only: [:create, :update, :destroy]
  end

  resource :user, only: [:show]

  devise_for :users, path: "auth"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  authenticated :user, ->(user) { user.admin? } do
    mount Resque::Server, at: "/jobs"
  end
end

app/models/user.rb
class User < ApplicationRecord
  include UniqueIdentifier
  include Flag

  unique_identifier "@", :username

  flag :flag, {
    deleted: "d",
  }

  has_paper_trail

  # Include default devise modules.
  # :database_authenticatable or :ldap_authenticatable
  # Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable, :recoverable, :rememberable, :validatable
  devise :ldap_authenticatable, :lockable, :rememberable

  enum :role, {
    user: 0,
    admin: 1,
    guest: 2,
  }, validate: true

  has_many :nodes, dependent: :restrict_with_error

  has_many :assignments, dependent: :destroy
  has_many :auth_assignments, -> { where(auth: true) },
    class_name: "Assignment", inverse_of: :user, dependent: nil
  has_many :use_assignments, -> { where(use: true) },
    class_name: "Assignment", inverse_of: :user, dependent: nil

  has_many :networks, through: :assignments
  has_many :auth_networks, through: :auth_assignments, source: :network
  has_many :use_networks, through: :use_assignments, source: :network

  validates :username, presence: true,
    uniqueness: {case_sensitive: true},
    length: {maximum: 255}
  validates :email, presence: true,
    length: {maximum: 255}
  validates :fullname, allow_blank: true, length: {maximum: 255}
  validates :limit, allow_nil: true,
    numericality: {only_integer: true, greater_than_or_equal_to: 0}

  validates_each :auth_network do |record, attr, value|
    if value && !value.auth
      record.errors.add(attr, I18n.t("errors.messages.not_auth_network"))
    end
  end

  after_save :allocate_network
  after_save :save_auth_network!

  after_commit :radius_user

  # class methods

  # rubocop: disable Lint/UnusedMethodArgument
  def self.ransackable_attributes(auth_object = nil)
    %w[username email fullname role deleted nodes_count]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
  # rubocop: enable Lint/UnusedMethodArgument

  def allocate_network
    return if @allocate_network_config.blank?

    if Settings.feature.user_auth_network &&
        @allocate_network_config[:auth_network]
      network = find_network(@allocate_network_config[:auth_network])
      unless network
        errors.add(:auth_network, I18n.t("errors.messages.no_allocate"))
        throw :abort
      end

      self.auth_network = network
      # assgimentを作成しておくために、セーブしておく
      save_auth_network!
    end

    @allocate_network_config[:networks]&.each_with_index do |net, idx|
      network = find_network(net)
      unless network
        errors.add(:use_networks, I18n.t("errors.messages.no_allocate"))
        throw :abort
      end

      add_use_network(network, default: idx == 0) || throw(:abort)
    end
  end

  private def find_network(net)
    case net
    when "free"
      Network.next_free_auth
    when "auth"
      auth_network
    else
      begin
        Network.find_identifier(net)
      rescue StandardError => e
        Rails.logger.warn "Not found #{net} network: #{e}"
        nil
      end
    end
  end

  # auto call this function before creat user by devise and user_sync
  def ldap_before_save
    sync_ldap!

    if Settings.admin.username == username
      # Set admin, and not allocate networks.
      admin!
      return
    end

    initial_configs = Settings.user_initial_configs.select do |conf|
      conf[:group].nil? || conf[:group] == "*" ||
        ldap_groups.include?(conf[:group])
    end.select do |conf|
      conf[:attribute].nil? ||
        conf[:attribute].all? do |k, v|
          if v == "*"
            !ldap_entry.first(k).nil?
          else
            ldap_entry[k].include?(v)
          end
       end
    end

    config = {
      auth_network: nil,
      networks: [],
      limit: nil,
      role: "user",
    }.merge(*initial_configs)

    @allocate_network_config = config.slice(:auth_network, :networks)
    self.limit = config[:limit]
    self.role = config[:role]
  end

  # TODO: devise_ldap_authenticatableのをそのまま使うのに変更予定
  def ldap_entry
    @ldap_entry ||= Devise::LDAP::Adapter.get_ldap_entry(username)
  end

  # TODO: devise_ldap_authenticatableのをそのまま使うのに変更予定
  def ldap_groups
    @ldap_groups ||= Devise::LDAP::Adapter.get_group_list(username)
  end

  def ldap_attributes
    @ldap_attributes ||= ldap_entry&.to_h
  end

  def ldap_mail
    ldap_entry&.first(Settings.ldap.user.attribute.mail)
  end

  def ldap_display_name
    attr = Settings.ldap.user.attribute.display_name
    locale_attr = "#{attr};lang-#{I18n.default_locale}"
    ldap_entry&.first(locale_attr) || ldap_entry&.first(attr)
  end

  def sync_ldap!
    unless ldap_entry
      errors.add(:username, "はLDAP上にないため、同期できません。")
      return
    end

    self.deleted = false
    self.email = ldap_mail
    self.fullname = ldap_display_name

    ldap_entry
  end

  def name
    @name ||=
      if fullname.present?
        "#{username} (#{fullname})"
      else
        username
      end
  end

  def deleted?
    deleted
  end

  def authorizable?
    Devise::LDAP::Adapter.authorizable?(username)
  end

  def auth_network_id
    auth_network&.id
  end

  def auth_network_id=(id)
    self.auth_network = id.presence && Network.find(id)
  end

  def auth_network
    unless @auth_network_acquired
      @auth_network = auth_networks.first
      @auth_network_acquired = true
    end

    @auth_network
  end

  def auth_network=(network)
    if network && !network.is_a?(Network)
      raise ActiveRecord::AssociationTypeMismatch,
        "Network expected, " \
        "got #{network.inspect} which is an instance of #{network.class}"
    end

    # no change
    return if network == auth_network

    @auth_network_change ||= [auth_network, nil]
    @auth_network_change[1] = network
    @auth_network_acquired = true
    @auth_network = network
  end

  def save_auth_network!
    return true unless auth_network_changed?

    Assignment.transaction do
      if auth_network
        auth_assignments.where.not(network: auth_network)
          .find_each do |assignment|
          assignment.update!(auth: false)
        end

        assignment = assignments.find_or_initialize_by(network: auth_network)
        assignment.update!(auth: true)
      else
        auth_assignments.find_each do |assignment|
          assignment.update!(auth: false)
        end
      end
    end

    @auth_network_previous_change = auth_network_change
    clear_auth_network_change
    true
  end

  def save_auth_network
    save_auth_network!
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
    false
  end

  attr_reader :auth_network_change, :auth_network_previous_change

  def auth_network_changed?
    auth_network_change.present?
  end

  def auth_network_previously_changed?
    auth_network_previous_change.present?
  end

  def auth_network_previously_was
    auth_network_previous_change&.first
  end

  def auth_network_was
    auth_network_change&.first
  end

  def auth_network_will_change!
    return if auth_network_changed?

    @auth_network_change = [auth_network, auth_network]
  end

  def clear_auth_network_change
    @auth_network_change = nil
  end

  def restore_auth_network!
    return unless auth_network_changed?

    @auth_network = auth_network_was
    clear_auth_network_change
  end

  def add_use_network(network, params = {})
    add_use_network_id(network.id, params)
  end

  def remove_use_network(network)
    remove_use_network_id(network.id)
  end

  def add_use_network_id(network_id, params = {})
    assignment = assignments.find_or_initialize_by(network_id:)
    assignment.use = true
    assignment.assign_attributes(params)

    result = assignment.save
    if result
      @usable_networks = nil
      @default_network = nil
      @manageable_networks = nil
    end
    result
  end

  def remove_use_network_id(network_id)
    assignment = assignments.find_by(network_id:)
    return if assignment.nil?

    result = assignment.update(use: false)
    if result
      @usable_networks = nil
      @default_network = nil
      @manageable_networks = nil
    end
    result
  end

  def clear_use_networks
    assignments.each do |assignment|
      assignment.update(use: false, manage: false)
    end
  end

  def usable_networks
    @usable_networks ||=
      if admin?
        Network.readonly
      else
        use_networks
      end
  end

  # NOTE: デフォルトネットワークがない場合は、最初のネットワークになる。
  def default_network
    @default_network ||=
      use_assignments.order(default: :desc, id: :asc).first&.network
  end

  def manageable_networks
    @manageable_networks ||=
      if admin?
        Network.readonly
      else
        usable_networks.select { |network| network.assignment.manage? }
      end
  end

  def usable_network_ids
    usable_networks.map(&:id)
  end

  def default_network_id
    default_network&.id
  end

  def manageable_network_ids
    manageable_networks.map(&:id)
  end


  def radius_user
    return unless Settings.feature.user_auth_network

    if destroyed?
      if !deleted? && auth_network.present?
        RadiusUserDelJob.perform_later(username)
      end
    elsif deleted_previously_changed? || auth_network_previously_changed?
      if !deleted? && auth_network.present?
        RadiusUserAddJob.perform_later(username, auth_network.vlan)
      else
        RadiusUserDelJob.perform_later(username)
      end
    end
  end

  def unlimited
    limit.nil?
  end

  def node_creatable?
    return true if admin?

    return false if limit && limit <= nodes_count
    return false if Settings.config.node_require_nic &&
      Settings.config.nic_require_network &&
      use_networks.count.zero?

    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Search

  before_action :set_user, only: [:show, :edit, :update]
  before_action :authorize_user, only: [:index]

  search_for User

  # GET /users
  # GET /users.json
  # GET /users.csv
  def index
    set_search
    @users = search(policy_scope(User)).includes(:auth_networks, :use_networks)
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to @user, notice: t_success(@user, :update)
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html do
          flash.now.alert = t_failure(@user, :update)
          render :show
        end
        format.json { render json: @user.errors, status: :unprocessable_content }
      end
    end
  end

  def sync
    # TODO: 未実装
  end

  private def set_user
    @user =
      if params[:id]
        User.includes(:auth_networks, :use_networks).find(params[:id])
      else
        current_user
      end
    authorize @user
  end

  private def authorize_user
    authorize User
  end

  private def user_params
    permitted_params = params.expect(
      user: [:limit,
      :unlimited,
      :role,
      :auth_network_id,])
    if ActiveRecord::Type::Boolean.new.cast(permitted_params.delete(:unlimited))
      permitted_params[:limit] = nil
    end
    permitted_params
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= turbo_frame_tag user do
  = bootstrap_form_with model: user, data: {turbo: false} do |f|
    dl
      = dt_dd_for user, :username do |username|
        = username
        = badge_for(user, :deleted)
      = dt_dd_for user, :email
      = dt_dd_for user, :fullname
      = dt_dd_tag "#{User.human_attribute_name(:nodes_count)} / " \
        "#{User.human_attribute_name(:limit)}" do
        .row
          .col-auto
            = user.nodes_count
          .col-auto
            | /
          .col-auto
            = f.number_field :limit, hide_label: true, wrapper: false,
              min: 0, step: 1
          = f.check_box :unlimited,
            wrapper: {class: "col-auto", style: "margin-bottom: 0 !important;"}
      = dt_dd_for user, :role do |_role|
        .row: .col-auto
          = f.collection_select :role, t_enums(:role), :first, :second,
            {hide_label: true, wrapper: false},
            disabled: current_user == user
      - if Settings.feature.user_auth_network
        = dt_dd_for user, :auth_network do |_auth_network|
          .row: .col-auto
            = f.collection_select :auth_network_id, Network.where(auth: true),
              :id, :name_vlan,
              {include_blank: t("values.none"), hide_label: true,
                wrapper: false,}

    = f.submit class: "btn btn-primary"
    =< link_to t("actions.cancel"), user, class: "btn btn-dark",
      data: {turbo: user.id.present?}

app/views/users/_list.html.slim
= turbo_frame_tag "users-list" do
  = paginate @users

  .mb-2
    .row.mb-2.fw-bold
      .col-2
        = User.human_attribute_name(:username)
        =< sort_link(:username)
      .col-2
        = User.human_attribute_name(:email)
        =< sort_link(:email)
      .col-2
        = User.human_attribute_name(:fullname)
        =< sort_link(:fullname)
      .col-1
        = User.human_attribute_name(:role)
      .col-1
        = User.human_attribute_name(:deleted)
        =< filter_link(:deleted)
      - if Settings.feature.user_auth_network
        .col-1
          = User.human_attribute_name(:auth_network)
      .col-2
        = User.human_attribute_name(:use_networks)
      .col-1
        = User.human_attribute_name(:nodes_count)
        =< sort_link(:nodes_count)

    - @users.each do |user|
      = link_to user, data: {turbo: false}, class: "row py-1 border-top" do
        .col-2 = user.username
        .col-2 = user.email
        .col-2 = user.fullname
        .col-1 = t_enum(user.role, :role)
        .col-1 = i_bool_tag(user.deleted)
        - if Settings.feature.user_auth_network
          .col-1 = user.auth_network&.identifier
        .col-2 = user.use_networks.map(&:identifier).join(", ")
        .col-1 = user.nodes_count

  = paginate @users
  p
    = page_entries_info @users

app/views/users/_use_network.html.slim
= turbo_frame_tag "#{dom_id(user)}_use_networks" do
  h4 = User.human_attribute_name(:networks)

  - if @user.use_networks.count.zero?
    p ユーザーに紐付けられたネットワークはありません。
  - else
    table.table.table-hover.table-sm
      thead
        tr
          th scope="col" = Network.human_attribute_name(:name)
          th scope="col" = Network.human_attribute_name(:vlan)
          th scope="col" = Network.human_attribute_name(:ipv4_network)
          th scope="col" = Network.human_attribute_name(:ipv6_network)
          th scope="col" = Assignment.human_attribute_name(:default)
          th scope="col" = Assignment.human_attribute_name(:manage)
          - if current_user.admin?
            th scope="col"
              | 操作
      tbody
        - @user.use_assignments.each do |assignment|
          - if (network = assignment.network)
            tr
              td
                = link_to network.name, network_path(network),
                  data: {turbo: false}
              td = network.vlan
              td = network.ipv4_network&.to_s
              td = network.ipv6_network&.to_s
              td = use_network_switch(assignment, :default)
              td = use_network_switch(assignment, :manage)
              - if current_user.admin?
                td
                  = button_to "解除", user_use_network_path(@user, network),
                    data: {turbo_confirm: "本当に解除しますか？"},
                    method: :delete, class: "btn btn-danger"
    - if current_user.admin?
      p ユーザーの紐付けを解除しても、端末への紐付けは削除されません。

  / TODO: モーダルで選択できるようにする
  - if current_user.admin?
    .mb-2
      - unregistered_networks = Network.where.not(id: @user.use_network_ids)
      - if unregistered_networks.exists?
        = bootstrap_form_with model: Assignment.new, url: user_use_networks_path(@user) do |f|
          .row.row-cols-md-auto.g-3.align-items-center
            .col-12
              = f.collection_select :network_id, unregistered_networks,
                :id, :name_vlan,
                {prompt: "(選択してください)", hide_label: true, wrapper: false},
                {required: true}
            .col-12
              = f.check_box :default, label: "デフォルト"
            .col-12
              = f.check_box :manage, label: "管理"
            .col-12
              = f.submit "追加", class: "btn btn-primary"
      - else
        p 登録できるネットワークはありません

app/views/users/_user.html.slim
= turbo_frame_tag user do
  dl
    = dt_dd_for user, :username do |username|
      = username
      = badge_for(user, :deleted)
    = dt_dd_for user, :email
    = dt_dd_for user, :fullname
    = dt_dd_tag "#{User.human_attribute_name(:nodes_count)} / " \
      "#{User.human_attribute_name(:limit)}" do
      => link_to nodes_path(condition: {user_id: user.id}),
        data: {turbo: false} do
        = user.nodes_count
      | /
      - if user.limit
        =< user.limit
      - else
        =< t("values.unlimited")
    = dt_dd_for user, :role do |role|
      = t_enum(role, :role)
    - if Settings.feature.user_auth_network
      = dt_dd_for user, :auth_network do |auth_network|
        = auth_network&.name_vlan || t("values.none")
  - if current_user.admin?
    =< link_to t("actions.edit"), edit_user_path(user),
      class: "btn btn-warning"

app/views/users/edit.html.slim
- content_for :heading
  h2
    = User.model_name.human

= render "form", user: @user

hr

= render "use_network", user: @user

app/views/users/index.html.slim
- content_for :heading
  h2
    = User.model_name.human
    = t("actions.index")

.mb-2
  .row.row-cols-md-auto.g-3.align-items-center
    .col-12
      = bootstrap_form_tag url: users_path, method: "get", data: {turbo_frame: "users-list"} do |f|
        = f.search_field :query, value: @query, hide_label: true,
          append: f.primary('<i class="fas fa-search"></i>'.html_safe,
            name: :search, render_as_button: true)
    .col-12
      = bootstrap_form_with model: Bulk.new(target: "User"), data: {turbo: false} do |f|
        = f.hidden_field :target
        = f.select :content_type, bulk_content_type_list,
          hide_label: true, prepend: t("forms.bulk.export"),
          append: f.primary('<i class="fa-solid fa-file-export"></i>'.html_safe, name: :commit, render_as_button: true)

= render "list"

app/views/users/show.html.slim
- content_for :heading
  h2
    = User.model_name.human

= render @user

hr

= render "use_network", user: @user

app/views/users/sync.html.slim
h1 Users#sync
p Find me in app/views/users/sync.html.slim