config/routes.rb
require "resque/server"
require "resque/scheduler/server"

Rails.application.routes.draw do
  root to: "pages#top"
  get "about", to: "pages#about"
  get "help/bulk", to: "pages#help_bulk"

  resources :nodes do
    member do
      post "transfer"
    end
    resource :confirmation, only: [:new, :edit, :create, :update]
    resource :specific_node_application, only: [:new, :create]
    resource :host
    resources :components, only: [:index, :show, :new, :update, :destroy]
  end
  resources :nics, only: [:show, :new]

  resources :networks
  resources :ipv4_pools, only: [:new]
  resources :ipv6_pools, only: [:new]

  resources :bulks, only: [:index, :show, :create, :destroy] do
    member do
      put "cancel"
    end
  end

  defaults format: :json do
    resources :places, only: [:index, :show, :create, :update, :destroy]
    resources :hardwares, only: [:index, :show, :create, :update, :destroy]
    resources :operating_systems,
      only: [:index, :show, :create, :update, :destroy]
    resources :security_softwares,
      only: [:index, :show, :create, :update, :destroy]
    resources :device_types, only: [:index, :show, :create, :update, :destroy]
    resources :os_categories, only: [:index, :show, :create, :update, :destroy]
  end

  namespace "manage" do
    get "places"
    get "hardwares"
    get "operating_systems"
    get "security_softwares"
    get "device_types"
    get "os_categories"
  end

  resources :users, only: [:index, :show, :edit, :update] do
    collection do
      put "sync"
    end
    resources :use_networks, only: [:create, :update, :destroy]
  end

  resource :user, only: [:show]

  devise_for :users, path: "auth"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  authenticated :user, ->(user) { user.admin? } do
    mount Resque::Server, at: "/jobs"
  end
end

app/models/bulk.rb
class Bulk < ApplicationRecord
  include CleanRecord

  has_paper_trail

  enum :status, {
    waiting: 0,
    starting: 1,
    running: 2,
    stopping: 3,
    stopped: 4,
    succeeded: 5,
    failed: 6,
    cancel: 7,
    error: 8,
    timeout: 9,
    nothing: 10,
  }, validate: true

  belongs_to :user
  has_one_attached :input
  has_one_attached :output

  validates :target, inclusion: {in: ["Node", "Confirmation", "Network", "User"]}
  validates :content_type, inclusion: {in: ["text/csv", "application/yaml", "application/jsonl"]}, allow_nil: true
  validates :input, presence: true, if: ->(bulk) { bulk.content_type.nil? }

  before_update :check_status_transition

  after_create_commit :register_job

  # class methods

  # rubocop: disable Lint/UnusedMethodArgument
  def self.ransackable_attributes(auth_object = nil)
    %w[
      id
      target
      status
      created_at
      updated_at
    ]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[users]
  end
  # rubocop: enable Lint/UnusedMethodArgument

  def check_status_transition
    case status_change
    in nil
      # ok
    in _, "error"
      # ok
    in "waiting" | "starting" | "running" | "stopping", _
      # ok
    in "stopped" | "succeeded" | "failed" | "cancel" | "error" | "timeout" |
      "nothing", _
      throw :abort
    else
      Rails.logger.warn("Unmatched pattern: #{status_change}")
      throw :abort
    end
  end

  def register_job
    if input.attached?
      BulkRunJob.set(wait: 1.second).perform_later(self)
    else
      BulkRunJob.perform_later(self)
    end
  end
end

app/controllers/bulks_controller.rb
class BulksController < ApplicationController
  include Search

  before_action :set_bulk, only: [:show, :destroy, :cancel]
  before_action :authorize_bulk, only: [:index]

  search_for Bulk

  # GET /bulks or /bulks.json
  def index
    set_search(order: {"id" => "desc"}, per: 20)
    @bulks = search(policy_scope(Bulk)).includes(:user)
  end

  # GET /bulks/1 or /bulks/1.json
  def show
    respond_to do |format|
      format.html do
        redirect_to bulks_url
      end
      format.json
    end
  end

  # POST /bulks or /bulks.json or /bulks.turbo_stream
  def create
    @bulk = Bulk.new(bulk_params)
    @bulk.user = current_user
    @bulk.status = "waiting"
    authorize @bulk

    respond_to do |format|
      if @bulk.save
        format.turbo_stream do
          flash.now.notice = t_success(@bulk, :register)
        end
        format.html do
          redirect_to bulks_url, notice: t_success(@bulk, :register)
        end
        format.json { render :show, status: :created, location: @bulk }
      else
        format.turbo_stream do
          flash.now.alert = t_failure(@bulk, :register)
        end
        format.html do
          redirect_to bulks_url, alert: t_failure(@bulk, :register)
        end
        format.json { render json: @bulk.errors, status: :unprocessable_content }
      end
    end
  end

  # PUT /bulks/1/cancel or /bulks/1/cancel.json
  def cancel
    respond_to do |format|
      if @bulk.update(status: :cancel)
        format.turbo_stream do
          flash.now.notice = t_success(@bulk, :cancel)
        end
        format.html do
          redirect_to bulks_url, notice: t_success(@bulk, :cancel)
        end
        format.json { render :show, status: :ok, location: @bulk }
      else
        @bulk.restore_status!
        format.turbo_stream do
          flash.now.alert = t_failure(@bulk, :cancel)
        end
        format.html do
          redirect_to bulks_url, alert: t_failure(@bulk, :cancel)
        end
        format.json { render json: @bulk.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /bulks/1 or /bulks/1.json
  def destroy
    if @bulk.destroy
      respond_to do |format|
        format.turbo_stream do
          flash.now.notice = t_success(@bulk, :delete)
        end
        format.html do
          redirect_to bulks_url, notice: t_success(@bulk, :delete)
        end
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          flash.now.alert = t_failure(@bulk, :delete)
        end
        format.html do
          redirect_to bulks_url, alert: t_failure(@bulk, :delete)
        end
        format.json { render json: @bulk.errors, status: :unprocessable_content }
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_bulk
    @bulk = Bulk.find(params[:id])
    authorize @bulk
  end

  # Only allow a list of trusted parameters through.
  private def bulk_params
    params.expect(bulk: [:target, :input, :content_type])
  end

  private def authorize_bulk
    authorize Bulk
  end
end

app/helpers/bulks_helper.rb
module BulksHelper
  BULK_LIST_COLS = [
    {name: :user,       grid: [0, 0, 0, 1, 1, 1], sort: :users_username},
    {name: :target,     grid: [0, 0, 2, 1, 1, 1], sort: :target},
    {name: :created_at, grid: [5, 5, 4, 4, 2, 2], sort: :created_at},
    {name: :updated_at, grid: [0, 0, 0, 0, 2, 2], sort: :updated_at},
    {name: :status,     grid: [2, 2, 2, 1, 1, 1], sort: :status},
    {name: :count,      grid: [0, 0, 0, 1, 1, 1]},
    {name: :input,      grid: [0, 0, 0, 1, 1, 1]},
    {name: :output,     grid: [2, 2, 2, 1, 1, 1]},
    {name: :action,     grid: [3, 3, 2, 2, 2, 2]},
  ].freeze

  def bulk_list_cols
    BULK_LIST_COLS
  end

  def bulk_targets
    if current_user.admin?
      [
        "Node",
        # "Confirmation",
        "Network",
        "User",
      ]
    else
      [
        "Node",
        # "Confirmation",
      ]
    end
  end

  def bulk_target_list
    bulk_targets.map do |target|
      [t(target.underscore, scope: "activerecord.models"), target]
    end
  end

  def bulk_content_type_list
    [
      ["CSV", "text/csv"],
      ["YAML", "application/yaml"],
      ["JSONL", "application/jsonl"],
    ]
  end
end

app/views/bulks/_bulk.html.slim
= turbo_frame_tag bulk do
  .row.py-1.border-bottom
    - bulk_list_cols.each do |col|
      = tag.div class: col_grid_class(col) do
        - case col[:name]
        - when :user
          = bulk.user&.username
        - when :target
          = t(bulk.target.underscore, scope: "activerecord.models")
        - when :created_at, :updated_at
          = span_value_for(bulk.__send__(col[:name]), format: :short)
        - when :status
          = t_enum(bulk.status, :status)
        - when :count
          = "#{bulk.number} (#{bulk.success}/#{bulk.failure})"
        - when :input, :output
          - attachment = bulk.__send__(col[:name])
          - if attachment.attached?
           = link_to attachment, class: "btn btn-primary", download: attachment.filename do
            i.fa-solid.fa-download
        - when :action
          - if %w(waiting starting running stopping).include?(bulk.status)
            =<> link_to cancel_bulk_path(bulk),
              data: { \
                turbo_method: :put,
                turbo_confirm: t("messages.confirm_cancel"),
              },
              class: "btn btn-warning" do
              i.fa-solid.fa-ban
            =<> link_to bulk, class: "btn btn-secondary" do
              i.fa-solid.fa-rotate-right
          - else
            =<> link_to bulk,
              data: { \
                turbo_method: :delete,
                turbo_confirm: t("messages.confirm_destroy"),
              },
              class: "btn btn-danger" do
              i.fa-regular.fa-trash-can
        - else
          = span_value_for(bulk.__send__(col[:name]))

app/views/bulks/_form.html.slim
= turbo_frame_tag bulk do
  = bootstrap_form_with model: bulk,
    data: {turbo_confirm: t("messages.confirm_register_bulk")} do |form|
    .row
      .col-sm-4.col-md-3.col-xl-2
          = form.select :target, bulk_target_list,
            hide_label: true, prepend: Bulk.human_attribute_name(:target)
      .col-sm-8.col-md-7.col-lg-6.col-xl-5
        = form.file_field :input, hide_label: true, accept: ".csv,.jsonl,.yaml,.yml"
      .col-sm-2
        = form.submit
  p
    => t("forms.bulk.help")
    | (
    = link_to t("messages.help_of_model", model: Bulk.model_name.human),
      help_bulk_path,
      target: "_blank", rel: "noopener", data: {turbo: false}
    | )

app/views/bulks/cancel.turbo_stream.slim
= turbo_stream.replace @bulk
= turbo_stream.replace "flash", partial: "flash"

app/views/bulks/create.turbo_stream.slim
- if @bulk.new_record?
  = turbo_stream.replace @bulk, partial: "form", locals: {bulk: @bulk}
- else
  = turbo_stream.prepend "bulks", @bulk
  = turbo_stream.replace Bulk.new, partial: "form",
    locals: {bulk: Bulk.new(target: @bulk.target)}
= turbo_stream.replace "flash", partial: "flash"

app/views/bulks/destroy.turbo_stream.slim
= turbo_stream.remove @bulk
= turbo_stream.update "flash", partial: "flash"

app/views/bulks/index.html.slim
- content_for :heading
  h2
    = Bulk.model_name.human
    = t("actions.index")

= render "form", bulk: Bulk.new

= turbo_frame_tag "bulks-list" do
  p = t("views.bulks.index.note", period: distance_of_time_in_words(Bulk.retention_period))
  .mb-2
    .row.py-1.border-bottom.fw-bold
      - bulk_list_cols.each do |col|
        = tag.div class: col_grid_class(col) do
          = Bulk.human_attribute_name(col[:name])
          - if col[:sort]
            =< sort_link(col[:sort])

  = turbo_frame_tag "bulks"
    = render @bulks

  = paginate @bulks

app/views/bulks/show.html.slim
= render @bulk